services:
  accounts:
    image: "rajeshanthari/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajeshanthari
  loans:
    image: "rajeshanthari/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajeshanthari
  cards:
    image: "rajeshanthari/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajeshanthari
networks:
  rajeshanthari:
    driver: "bridge"