spring:
  application:
    name: "gatewayserver"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    gateway:
      discovery:
        locator: 
          enabled: false
          lowerCaseServiceId: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
      
info:
  app:
    name: "gatewayserver"
    description: "Bank gateway server application"
    version: "1.0.0"
    
logging:
  level:
    com:
      rajeshanthari:
        ms: DEBUG